import type {
  AntiAiRuleType,
  AntiAiSeverity,
  CharacterRules,
  LanguageRules,
  NarrativeRules,
  RhythmRules,
} from "@ai-novel/shared/types/styleEngine";

export interface DefaultTemplateDefinition {
  key: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  applicableGenres: string[];
  analysisMarkdown: string;
  narrativeRules: NarrativeRules;
  characterRules: CharacterRules;
  languageRules: LanguageRules;
  rhythmRules: RhythmRules;
  defaultAntiAiRuleKeys: string[];
}

export interface DefaultAntiAiRuleDefinition {
  key: string;
  name: string;
  type: AntiAiRuleType;
  severity: AntiAiSeverity;
  description: string;
  detectPatterns: string[];
  rewriteSuggestion: string;
  promptInstruction: string;
  autoRewrite: boolean;
  enabled: boolean;
  globalBaselineEnabled: boolean;
}

export interface DefaultStarterStyleProfileDefinition {
  key: string;
  templateKey: string;
  name: string;
  description: string;
}

export const DEFAULT_STYLE_TEMPLATES: DefaultTemplateDefinition[] = [
  {
    key: "bottom-loop-reality",
    name: "底层循环现实流",
    description: "通过碎片化生活与反复落空表现人物困境。",
    category: "现实流",
    tags: ["第一人称", "口语化", "碎片叙事"],
    applicableGenres: ["都市", "现实", "成长"],
    analysisMarkdown: "以时间推进和现实落差构成叙事张力，结尾不解决核心困境。",
    narrativeRules: {
      progressionMode: "time_sequence",
      sceneUnitPattern: ["行为", "落差", "自我合理化"],
      multiPov: false,
      looping: true,
      endingStyle: "unresolved",
      summary: "以碎片化生活推进，不做总括式回顾。",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "behavior_only",
      defenseMechanisms: ["嘴硬", "转移", "自我合理化"],
      facePriority: true,
      dialogueStyle: "short_colloquial",
      summary: "人物情绪通过动作和嘴硬表达。",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.8,
      allowIncompleteSentences: true,
      allowSwearing: true,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "语言粗粝、口语化，允许生活杂音。",
    },
    rhythmRules: {
      pace: "medium_fast",
      paragraphDensity: "high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "段落密实，动作先于解释。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-ending-elevation",
      "encourage-useless-action",
      "encourage-reality-gap",
      "encourage-hard-mouth-compensation",
    ],
  },
  {
    key: "power-up-escalation",
    name: "爽文递进推进流",
    description: "持续升级冲突和收益点，强化目标推进与爽点兑现。",
    category: "爽文流",
    tags: ["推进感", "收益点", "冲突升级"],
    applicableGenres: ["都市", "玄幻", "热血"],
    analysisMarkdown: "每段都要有目标推进或爽点兑现，保持明确因果和节奏抬升。",
    narrativeRules: {
      progressionMode: "goal_driven",
      sceneUnitPattern: ["目标", "阻碍", "压制", "反转收益"],
      multiPov: false,
      looping: false,
      endingStyle: "hook",
      summary: "围绕目标推进，尽快兑现局部收益。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "dialogue_and_action",
      defenseMechanisms: [],
      facePriority: false,
      dialogueStyle: "direct",
      summary: "角色表达直接，情绪跟随胜负切换。",
    },
    languageRules: {
      register: "direct",
      roughness: 0.55,
      allowIncompleteSentences: false,
      allowSwearing: false,
      sentenceVariation: "medium",
      allowUselessDetails: false,
      summary: "句式清晰，减少无效分散信息。",
    },
    rhythmRules: {
      pace: "fast",
      paragraphDensity: "medium",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "优先冲突和结果，少停留。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-theme-summary",
      "risk-dialogue-too-functional",
      "risk-three-paragraphs-exposition",
    ],
  },
  {
    key: "suspense-pressure",
    name: "悬疑压迫递增流",
    description: "通过信息遮蔽、细节异常和压力叠加制造不安感。",
    category: "悬疑流",
    tags: ["压迫感", "信息差", "异常细节"],
    applicableGenres: ["悬疑", "惊悚", "现实"],
    analysisMarkdown: "以异常细节、信息差和节奏收束推动悬念层层加压。",
    narrativeRules: {
      progressionMode: "mystery_escalation",
      sceneUnitPattern: ["现场细节", "异常", "误判", "新风险"],
      multiPov: false,
      looping: false,
      endingStyle: "suspense",
      summary: "优先制造信息缺口和压迫氛围。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "reaction_only",
      defenseMechanisms: ["压抑"],
      facePriority: false,
      dialogueStyle: "restrained",
      summary: "角色反应克制，恐惧通过反应显现。",
    },
    languageRules: {
      register: "restrained",
      roughness: 0.45,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "medium_high",
      allowUselessDetails: true,
      summary: "细节精确，保留少量噪音增强现场感。",
    },
    rhythmRules: {
      pace: "medium",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "通过节奏收束和信息延迟制造压力。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-theme-summary",
      "risk-even-paragraph-length",
      "encourage-reality-gap",
    ],
  },
  {
    key: "emotional-tension",
    name: "情绪拉扯流",
    description: "通过错位表达、停顿和误读制造关系张力。",
    category: "情感流",
    tags: ["误读", "拉扯", "停顿感"],
    applicableGenres: ["言情", "都市", "群像"],
    analysisMarkdown: "人物不直说核心情绪，靠误读、停顿和反应推动关系变化。",
    narrativeRules: {
      progressionMode: "relationship_push_pull",
      sceneUnitPattern: ["动作", "言外之意", "误读", "回避"],
      multiPov: false,
      looping: false,
      endingStyle: "emotional_hook",
      summary: "以关系错位推进，而非直接说明。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "subtext",
      defenseMechanisms: ["回避", "试探", "嘴硬"],
      facePriority: true,
      dialogueStyle: "subtext_heavy",
      summary: "情绪通过停顿、动作和言外之意体现。",
    },
    languageRules: {
      register: "natural",
      roughness: 0.35,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "语言自然，允许留白与停顿。",
    },
    rhythmRules: {
      pace: "medium_slow",
      paragraphDensity: "medium",
      allowFragmentedFlow: true,
      actionOverExplanation: false,
      summary: "给关系反应留空间，但避免空洞抒情。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-direct-preaching",
      "forbid-ending-elevation",
      "risk-dialogue-too-functional",
      "encourage-useless-action",
    ],
  },
  {
    key: "ensemble-weave",
    name: "群像交织流",
    description: "以多人行动线和视角差异交织推进事件。",
    category: "群像流",
    tags: ["多角色", "交织", "信息流动"],
    applicableGenres: ["群像", "都市", "悬疑"],
    analysisMarkdown: "多角色并行推进，但每个角色的表达和认知范围必须区分清楚。",
    narrativeRules: {
      progressionMode: "multi_thread",
      sceneUnitPattern: ["角色动作", "局部信息", "交叉影响"],
      multiPov: true,
      looping: false,
      endingStyle: "cross_hook",
      povSwitchStyle: "controlled",
      summary: "多线并进，但视角切换要受控。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "mixed",
      defenseMechanisms: [],
      facePriority: false,
      dialogueStyle: "distinct_by_role",
      summary: "不同角色口吻必须拉开差异。",
    },
    languageRules: {
      register: "flexible",
      roughness: 0.45,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "high",
      allowUselessDetails: false,
      summary: "保持角色差异，避免所有人说话一样。",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "medium",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "多线交织但节奏不乱。",
    },
    defaultAntiAiRuleKeys: [
      "risk-dialogue-too-functional",
      "risk-repeated-sentence-structure",
      "forbid-theme-summary",
    ],
  },
  {
    key: "immersive-daily",
    name: "日常浸没流",
    description: "通过生活细节和细微情绪变化建立持续沉浸感。",
    category: "日常流",
    tags: ["生活感", "沉浸", "细碎细节"],
    applicableGenres: ["日常", "治愈", "都市"],
    analysisMarkdown: "允许保留生活性动作和无效信息，但核心情绪仍要通过场景自然流出。",
    narrativeRules: {
      progressionMode: "scene_immersion",
      sceneUnitPattern: ["动作", "环境", "关系反应"],
      multiPov: false,
      looping: false,
      endingStyle: "soft_open",
      summary: "重场景体验和关系温度。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "light_behavior",
      defenseMechanisms: [],
      facePriority: false,
      dialogueStyle: "daily_natural",
      summary: "人物表达自然，不用高强度戏剧句。",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.25,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "medium_high",
      allowUselessDetails: true,
      summary: "保留生活细节和杂音，不追求工整。",
    },
    rhythmRules: {
      pace: "slow",
      paragraphDensity: "medium",
      allowFragmentedFlow: true,
      actionOverExplanation: false,
      summary: "慢节奏沉浸，但避免空转。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-ending-elevation",
      "risk-even-paragraph-length",
      "encourage-useless-action",
    ],
  },
  {
    key: "cold-professional",
    name: "冷峻专业流",
    description: "以专业事实和行业细节压住情绪，形成克制压力感。",
    category: "专业流",
    tags: ["专业细节", "克制", "事实压情绪"],
    applicableGenres: ["职场", "现实", "悬疑"],
    analysisMarkdown: "行业事实和程序细节优先，情绪不直说，信息密度高于抒情密度。",
    narrativeRules: {
      progressionMode: "fact_driven",
      sceneUnitPattern: ["事实", "动作", "专业判断", "后果"],
      multiPov: false,
      looping: false,
      endingStyle: "pressure_continue",
      summary: "让专业事实承担叙事重量。",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "suppressed",
      defenseMechanisms: ["克制"],
      facePriority: false,
      dialogueStyle: "informational",
      summary: "情绪藏在专业动作和事实选择里。",
    },
    languageRules: {
      register: "professional",
      roughness: 0.2,
      allowIncompleteSentences: false,
      allowSwearing: false,
      sentenceVariation: "medium",
      allowUselessDetails: false,
      summary: "术语和事实优先，避免廉价金句。",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "信息密度高，但不铺张解释。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-direct-preaching",
      "forbid-theme-summary",
      "risk-repeated-sentence-structure",
    ],
  },
  {
    key: "absurd-dark-humor",
    name: "荒诞黑色幽默流",
    description: "通过反差、冷感观察和荒诞细节制造黑色幽默。",
    category: "黑色幽默",
    tags: ["荒诞", "反差", "冷感"],
    applicableGenres: ["都市", "黑色幽默", "现实"],
    analysisMarkdown: "用反差和荒诞细节放大现实困境，笑点和压迫感同时存在。",
    narrativeRules: {
      progressionMode: "contrast_driven",
      sceneUnitPattern: ["现实细节", "荒诞偏差", "冷反应"],
      multiPov: false,
      looping: false,
      endingStyle: "bitter_aftertaste",
      summary: "依赖反差和冷感观察，而非热闹吐槽。",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "deadpan",
      defenseMechanisms: ["自嘲", "转移"],
      facePriority: true,
      dialogueStyle: "deadpan_colloquial",
      summary: "情绪藏在冷反应和嘴硬里。",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.5,
      allowIncompleteSentences: true,
      allowSwearing: true,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "允许夹带荒诞杂质和冷幽默节奏。",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "反差点要快落地，不要解释笑点。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-ending-elevation",
      "encourage-reality-gap",
      "encourage-hard-mouth-compensation",
    ],
  },
  {
    key: "jinyong-wuxia-classic",
    name: "金庸古典武侠流",
    description: "以白描见情义、以情节藏人心；招式是壳，人是核。",
    category: "武侠流",
    tags: ["古典白描", "情义驱动", "江湖传奇"],
    applicableGenres: ["武侠", "仙侠", "历史传奇", "古典权谋"],
    analysisMarkdown: "大开大合的传奇结构，情义恩仇驱动人物；白描见功力，武打写势与意而非术语。",
    narrativeRules: {
      progressionMode: "legend_arc",
      sceneUnitPattern: ["际遇", "恩怨", "考验", "命运转折"],
      multiPov: false,
      looping: false,
      endingStyle: "hook",
      summary: "走大开大合的传奇路线：主角从微末一步步卷入更大的江湖恩怨与家国格局。转折多用巧合中的必然（重逢、误会、身世揭破），但每个转折都要在前文埋过伏笔，绝不天降。视角贴着主角走，世界观随脚步徐徐展开，不要一次性倾倒设定。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "action_and_dialogue",
      defenseMechanisms: [],
      facePriority: true,
      dialogueStyle: "classic_terse",
      summary: "人物先有性情再有武功，性格即命运。恩、义、情、信是行动的真正驱动，打斗只是它的外化。配角也要立得住，三百字的小人物也得有鲜明脾性与说话方式。反派不脸谱化，有自己的逻辑与悲哀。",
    },
    languageRules: {
      register: "classical_vernacular",
      roughness: 0.3,
      allowIncompleteSentences: false,
      allowSwearing: false,
      sentenceVariation: "high",
      allowUselessDetails: false,
      summary: "以白描为主，干净利落，文白相间而不掉书袋；多用短句推进，长句只在抒情处。对话见功力，寥寥数语显身份、机锋与情绪，少用他愤怒地说这类附注。景物点到为止，永远服务于气氛与情节。",
    },
    rhythmRules: {
      pace: "medium_fast",
      paragraphDensity: "medium",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "张弛分明：紧张对决之后给一段江湖人情的喘息，再起波澜。武打写攻防的势、意与心理博弈，不堆招式术语，让外行也看得心跳。关键处舍得放慢一笔写人心。",
    },
    defaultAntiAiRuleKeys: [
      "encourage-jinyong-chivalry-voice",
      "forbid-explicit-psychology",
      "forbid-theme-summary",
      "risk-repeated-sentence-structure",
    ],
  },
  {
    key: "tianxia-bachang-folk-horror",
    name: "天下霸唱诡谲探险流",
    description: "用最接地气的口吻讲最邪门的事；越镇定地叙述诡异越渗人。",
    category: "悬疑流",
    tags: ["口述讲古", "诡谲冷处理", "知识流细节"],
    applicableGenres: ["盗墓", "探险", "灵异悬疑", "民俗怪谈"],
    analysisMarkdown: "第一人称口述讲古，危机驱动，知识流做实诡异，章末必留诡象钩子。",
    narrativeRules: {
      progressionMode: "expedition_escalation",
      sceneUnitPattern: ["进入险地", "规矩与机关", "怪象", "更大的未知"],
      multiPov: false,
      looping: false,
      endingStyle: "suspense",
      summary: "第一人称口述感强，像老江湖坐你对面讲古，可信带劲有烟火气。悬念层层递进：进一处险地，规矩、机关、怪象一环扣一环，每解开一个谜又冒出更大的谜。几乎每章都有一个迫在眉睫的险境逼着往前走。",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "behavior_and_banter",
      defenseMechanisms: ["插科打诨", "嘴硬"],
      facePriority: true,
      dialogueStyle: "colloquial_banter",
      summary: "主角组嘴贫但靠谱：插科打诨缓解紧张，关键时刻又拿得出真本事，反差出魅力。用行话、绰号、行规塑造圈子感，人物自带江湖来历。义气是底色，但表达粗粝、不矫情，靠行动证明。",
    },
    languageRules: {
      register: "colloquial_northern",
      roughness: 0.65,
      allowIncompleteSentences: true,
      allowSwearing: true,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "口语化、北方味、节奏快，敢用俚语和糙话，但糙得有分寸有幽默。叙述诡异之物时偏用平静甚至调侃的口吻，靠这种冷处理制造极强的恐怖反差。长于气味、声音、触感、温度等可感细节，让未知近在咫尺。",
    },
    rhythmRules: {
      pace: "fast",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "快节奏，事件密集险情接踵，几乎不留水段。紧张到缓口气（靠贫嘴插科）再到更紧张，把读者按在过山车上。章末几乎必留钩子：一个声音、一道影子、一个不对劲。",
    },
    defaultAntiAiRuleKeys: [
      "encourage-folk-horror-voice",
      "encourage-life-noise",
      "forbid-theme-summary",
      "risk-dialogue-too-functional",
    ],
  },
  {
    key: "liucixin-hard-scifi",
    name: "刘慈欣硬科幻流",
    description: "用冷峻的笔写炽热的想象；在宇宙尺度下逼问人性与文明。",
    category: "科幻流",
    tags: ["宏大叙事", "点子驱动", "冷峻克制"],
    applicableGenres: ["科幻", "末世", "星际文明"],
    analysisMarkdown: "尺度跃迁制造宏大眩晕，点子驱动，宏细节奇观具象化，语言冷峻克制。",
    narrativeRules: {
      progressionMode: "idea_driven_escalation",
      sceneUnitPattern: ["设想", "奇观", "文明抉择", "更大危机"],
      multiPov: true,
      looping: false,
      endingStyle: "suspense",
      povSwitchStyle: "controlled",
      summary: "尺度跳跃：从一个人的命运瞬间拉到文明、宇宙、亿万年的尺度，制造宏大的眩晕感。核心是一个震撼的科学设想或文明困境，情节为展开这个设想服务。危机层层升级，赌注不断翻倍。善用宏细节，用一个极具画面感的奇观镜头把抽象概念砸进读者脑里。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "suppressed",
      defenseMechanisms: ["理性克制"],
      facePriority: false,
      dialogueStyle: "informational",
      summary: "人物常是文明的切片，他们的选择承载某种立场或人性命题，而非小情小爱。冷静、理性、有担当的角色更突出；情感克制，但在关键时刻爆发出巨大的重量。靠在极端情境下如何抉择来立人，而非日常细节堆砌。",
    },
    languageRules: {
      register: "precise_restrained",
      roughness: 0.2,
      allowIncompleteSentences: false,
      allowSwearing: false,
      sentenceVariation: "medium",
      allowUselessDetails: false,
      summary: "冷峻、精确、克制，带工程师式的理性与说服力；偶尔迸出诗意金句，反差极强。描写奇观时画面感极强、信息密度高，让人看见从未见过的东西。科学设定讲得清楚可信但服务于震撼而非炫技，解释适可而止，留想象空间。关键处用短句下断语，制造命运感。",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "张力靠赌注升级而非事件密度维持。铺垫、蓄势，然后在某一刻给出认知颠覆的爆点，节奏服务于思想冲击的释放。章末钩子常是一个更大的谜或更绝望的处境，逼读者追问然后呢。",
    },
    defaultAntiAiRuleKeys: [
      "encourage-hard-scifi-voice",
      "forbid-explicit-psychology",
      "forbid-direct-preaching",
      "risk-three-paragraphs-exposition",
    ],
  },
];

export const DEFAULT_STARTER_STYLE_PROFILES: DefaultStarterStyleProfileDefinition[] = [
  {
    key: "starter-power-up",
    templateKey: "power-up-escalation",
    name: "我的默认爽文推进写法",
    description: "适合第一次开书先跑顺目标推进、爽点兑现和章节收益点，后续可以直接在此基础上微调。",
  },
  {
    key: "starter-suspense",
    templateKey: "suspense-pressure",
    name: "我的默认悬疑压迫写法",
    description: "适合异常、规则、调查和危险逼近类故事，先帮你把压迫感和信息差稳住。",
  },
  {
    key: "starter-emotional",
    templateKey: "emotional-tension",
    name: "我的默认情绪拉扯写法",
    description: "适合关系推进、误读拉扯和情绪兑现类故事，先有一套能直接开写的关系型表达底座。",
  },
  {
    key: "starter-daily",
    templateKey: "immersive-daily",
    name: "我的默认日常浸没写法",
    description: "适合治愈、陪伴、生活经营和轻缓成长类故事，优先保证生活感和沉浸感。",
  },
  {
    key: "starter-jinyong",
    templateKey: "jinyong-wuxia-classic",
    name: "金庸古典武侠写法",
    description: "适合武侠、仙侠、历史传奇：以白描和情义驱动，武打写势与意，江湖恩怨大开大合。",
  },
  {
    key: "starter-tianxia-bachang",
    templateKey: "tianxia-bachang-folk-horror",
    name: "天下霸唱诡谲探险写法",
    description: "适合盗墓、探险、灵异悬疑：第一人称口述讲古，知识流做实诡异，章末诡象钩子。",
  },
  {
    key: "starter-liucixin",
    templateKey: "liucixin-hard-scifi",
    name: "刘慈欣硬科幻写法",
    description: "适合硬科幻、末世、星际文明：尺度跃迁的宏大叙事，点子驱动，语言冷峻克制。",
  },
];

export const DEFAULT_ANTI_AI_RULES: DefaultAntiAiRuleDefinition[] = [
  {
    key: "forbid-explicit-psychology",
    name: "禁止解释型心理描写",
    type: "forbidden",
    severity: "high",
    description: "禁止直接使用“他感到”“他意识到”等句式解释人物心理。",
    detectPatterns: ["他感到", "她感到", "他意识到", "她意识到", "他明白了", "她明白了"],
    rewriteSuggestion: "把心理解释改成动作、语气、停顿、环境反应或结果。",
    promptInstruction: "禁止直接解释人物心理，人物状态必须通过行为、动作、语气或环境反应体现。",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "forbid-ending-elevation",
    name: "禁止段尾升华",
    type: "forbidden",
    severity: "high",
    description: "禁止在段尾或收尾处用总结句升华主题。",
    detectPatterns: ["生活就是", "命运总会", "归根结底", "说到底", "这就是"],
    rewriteSuggestion: "删除升华句，回到具体动作、现场或悬而未决的处境。",
    promptInstruction: "禁止段尾升华或总结主题，收尾必须落回具体情境。",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "forbid-theme-summary",
    name: "禁止总结主题",
    type: "forbidden",
    severity: "high",
    description: "禁止把段落写成总结中心思想或提炼人生道理。",
    detectPatterns: ["这说明", "这意味着", "归根结底", "其实就是"],
    rewriteSuggestion: "删掉主题总结，让信息通过事件和结果自然显现。",
    promptInstruction: "不要总结主题，不要替读者提炼中心思想。",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "forbid-direct-preaching",
    name: "禁止直接说教",
    type: "forbidden",
    severity: "medium",
    description: "禁止作者替角色或读者做直接价值判断和说教。",
    detectPatterns: ["我们都应该", "人总要学会", "真正重要的是"],
    rewriteSuggestion: "改成角色具体处境或对话，不做抽象说教。",
    promptInstruction: "禁止直接说教或价值判断，让意义落在事件本身。",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-even-paragraph-length",
    name: "段落长度过于整齐",
    type: "risk",
    severity: "medium",
    description: "段落长度和节奏过于平均，容易产生 AI 作文感。",
    detectPatterns: ["段落整齐", "节奏平均"],
    rewriteSuggestion: "打破段落长度均衡，让句子和段落有自然起伏。",
    promptInstruction: "注意避免每段都过于工整、平均和像标准作文。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-three-paragraphs-exposition",
    name: "连续三段解释性叙事",
    type: "risk",
    severity: "high",
    description: "连续几段只有解释没有动作，会削弱现场感。",
    detectPatterns: ["连续解释", "没有动作"],
    rewriteSuggestion: "插入动作、对话、环境反馈，减少连段说明。",
    promptInstruction: "注意避免连续几段只有解释没有动作或对话。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-dialogue-too-functional",
    name: "对话纯功能推进",
    type: "risk",
    severity: "medium",
    description: "对话只有信息推进，没有人物语气和生活噪音。",
    detectPatterns: ["告诉你", "我们现在要", "接下来就"],
    rewriteSuggestion: "补入停顿、绕弯、语气差异和无效信息。",
    promptInstruction: "对话不要只承担推进剧情功能，要保留人物语气和生活噪音。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-repeated-sentence-structure",
    name: "句式重复率过高",
    type: "risk",
    severity: "medium",
    description: "连续句式过于整齐，容易显得机械。",
    detectPatterns: ["首先", "然后", "接着", "最后"],
    rewriteSuggestion: "拉开句式长度和起句方式，打散结构。",
    promptInstruction: "警惕连续句式重复和排比化表达。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "encourage-useless-action",
    name: "鼓励无意义小动作",
    type: "encourage",
    severity: "low",
    description: "鼓励加入真实但不推动主线的小动作增强人味。",
    detectPatterns: [],
    rewriteSuggestion: "补入挠头、点烟、抠包装、挪椅子等小动作。",
    promptInstruction: "优先加入真实但不推动主线的小动作，增加生活感。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-reality-gap",
    name: "鼓励现实落差",
    type: "encourage",
    severity: "low",
    description: "让人物预期和现实结果之间出现落差。",
    detectPatterns: [],
    rewriteSuggestion: "补出人物预期与实际结果之间的差距。",
    promptInstruction: "优先制造现实落差，让人物预期和结果不完全一致。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-hard-mouth-compensation",
    name: "鼓励嘴硬补偿",
    type: "encourage",
    severity: "low",
    description: "人物吃瘪后用嘴硬、转移或找补来维持体面。",
    detectPatterns: [],
    rewriteSuggestion: "给角色补一句嘴硬找补或自我合理化。",
    promptInstruction: "人物吃瘪后可用嘴硬、转移或找补来补偿体面。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-life-noise",
    name: "鼓励生活噪音",
    type: "encourage",
    severity: "low",
    description: "适当加入与主线不完全相关的生活噪音增加现场感。",
    detectPatterns: [],
    rewriteSuggestion: "补入环境声、杂音、小打断或生活性信息。",
    promptInstruction: "适当保留生活噪音和无效信息，增强现场感。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-jinyong-chivalry-voice",
    name: "鼓励金庸式武侠笔法",
    type: "encourage",
    severity: "medium",
    description: "以白描与情义驱动呈现江湖，武打写势与意。",
    detectPatterns: [],
    rewriteSuggestion: "把抽象心理改成具体动作、对话与江湖细节；武打写攻防的势与心理博弈。",
    promptInstruction: "优先用白描与具体动作呈现江湖；让恩、义、情、信驱动人物抉择；武打要写攻防的势、意与心理博弈，不堆招式术语；对话寥寥数语显身份与机锋；语言文白相间但不掉书袋，景物点到为止服务情节。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-folk-horror-voice",
    name: "鼓励霸唱式讲古笔法",
    type: "encourage",
    severity: "medium",
    description: "第一人称口述讲古，冷处理诡异，知识流做实。",
    detectPatterns: [],
    rewriteSuggestion: "改成老江湖讲古口吻；诡异处用平静冷处理；补风水机关民俗细节；章末留诡象钩子。",
    promptInstruction: "用第一人称老江湖讲古的口吻叙述，可信带劲有烟火气；越诡异越用平静甚至略带调侃的冷处理，靠反差渗人；用风水、机关、民俗等知识细节把怪事做实；每章逼近一个迫在眉睫的险境，章末留一个不对劲的诡象钩子。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-hard-scifi-voice",
    name: "鼓励刘慈欣式硬科幻笔法",
    type: "encourage",
    severity: "medium",
    description: "尺度跃迁的宏大叙事，点子驱动，冷峻克制。",
    detectPatterns: [],
    rewriteSuggestion: "在个人与文明尺度间跳跃；围绕核心设想推进；用奇观镜头具象化；语言冷峻克制。",
    promptInstruction: "在个人与文明、宇宙尺度之间跳跃制造宏大感；围绕一个核心科学设想推进情节；用极具画面感的奇观镜头把抽象概念具象化；语言冷峻、精确、克制，情感留到关键处再爆发；解释科学适可而止，给读者留想象空间。",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
];
